# 使用官方的 Node.js 基础镜像
FROM node:22-alpine

# 检查 npm 是否安装
RUN which npm

# 设置工作目录为 /app
WORKDIR /app

# 将本地的 package.json 和 package-lock.json 文件复制到容器中
COPY package*.json ./

# 安装项目依赖
RUN npm install

# 如果你的应用需要构建步骤，运行构建命令
RUN npm run build

# 将本地的源代码复制到容器中
COPY . .

# 暴露端口，这里假设你的应用运行在 3000 端口
EXPOSE 3000

# 定义环境变量，如果需要的话
ENV NODE_ENV=development

# 启动应用
CMD ["npm", "start"]