# 使用完整版 Node.js 镜像
FROM node:20

# 设置工作目录为 /app
WORKDIR /app

# 将本地的 package.json 和 package-lock.json 文件复制到容器中
COPY package*.json ./

# 安装项目依赖
RUN npm install

# 重新安装 sqlite3，确保二进制文件正确
RUN npm rebuild sqlite3

# 将本地的源代码复制到容器中
COPY . .

# 如果你的应用需要构建步骤，运行构建命令
RUN npm run build

# 暴露端口，这里假设你的应用运行在 3000 端口
EXPOSE 3000

# 启动应用
CMD ["npm", "start"]